name: Release

on:
  workflow_dispatch:

jobs:
  submit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      
      - run: bun install

      - name: Zip extensions
        run: |
          bun zip
          bun zip:firefox

      # - name: Submit to stores
      #   run: |
      #     pnpm wxt submit \
      #       --chrome-zip .output/*-chrome.zip \
      #       --firefox-zip .output/*-firefox.zip --firefox-sources-zip .output/*-sources.zip

      - uses: actions/upload-artifact@v4
        with:
          name: chibisafe-uploader-chrome
          path: .output/chrome-mv3
          compression-level: 0

      - uses: actions/upload-artifact@v4
        with:
          name: chibisafe-uploader-firefox
          path: .output/firefox-mv2
          compression-level: 0

        # env:
        #   CHROME_EXTENSION_ID: ${{ secrets.CHROME_EXTENSION_ID }}
        #   CHROME_CLIENT_ID: ${{ secrets.CHROME_CLIENT_ID }}
        #   CHROME_CLIENT_SECRET: ${{ secrets.CHROME_CLIENT_SECRET }}
        #   CHROME_REFRESH_TOKEN: ${{ secrets.CHROME_REFRESH_TOKEN }}
        #   FIREFOX_EXTENSION_ID: ${{ secrets.FIREFOX_EXTENSION_ID }}
        #   FIREFOX_JWT_ISSUER: ${{ secrets.FIREFOX_JWT_ISSUER }}
        #   FIREFOX_JWT_SECRET: ${{ secrets.FIREFOX_JWT_SECRET }}
